#! /bin/sh
[ -f "$HOME/.Xmodmap" ] && xmodmap "$HOME/.Xmodmap"
pgrep -x sxhkd >/dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

xrdb -merge ~/.Xresources

bspc monitor DisplayPort-0 -d 一 二 三
bspc monitor DisplayPort-2 -d 四 五 六
bspc monitor DisplayPort-1 -d 七 八 九

bash ~/.config/bspwm/scripts/autostart.sh

bspc config pointer_follows_monitor true
# bspc config pointer_follows_focus true

bspc config border_width 4
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
